### ISSUE TITLE
activateNextStep not working

### ISSUE THREAD

**Issue by boytun** [williamabbott/accordion-wizard#16]
Really very nice plugin.
Please how we can use activateNextStep, can you provide a demo for this function or how to initialise this function in a basic code.
When I use it the debugger show that this function is not definedb but the accordion system work like a charm.

**Comment by wrabit** [comment]
I can't remember why this was there, probably left from an abandoned feature idea. Is it something you still need? How do you envision it working?

**Comment by GKdeVries** [comment]
Little late to the party, but it looks like the documentation about this is incorrect.
In my case it worked flawless with the following:
$('#element').data(**'plugin_accordionForm'**).activateNextStep();
